apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-api
  namespace: kitchen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-api
  template:
    metadata:
      labels:
        app: kitchen-api
    spec:
      containers:
      - name: kitchen-api
        image: kitchen-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/kitchen