version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: kitchen-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    container_name: kitchen-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo-data: